{% set python_min = "3.10" %}
{% set name = "paradoc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Krande/paradoc/archive/v{{ version }}.tar.gz
  sha256: b5b0ba186090f9c83aeece75fa6de51ed5a09fc860aab6f3c74b5f46b221f04f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - paradoc=paradoc.cli_app:app

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandoc 3.1.2
    - pandoc-crossref 0.3.16
    - pypandoc 1.12
    - python-docx
    - docxcompose
    - numpy
    - pandas
    - openpyxl
    - tabulate
    - svgwrite
    - pytexit
    - typer
    - __unix  # [unix]
    - __win   # [win]
    - pywin32  # [win]
test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - pytest-cov
    - python {{ python_min }}
  commands:
    - cd tests
    - pytest

about:
  home: https://github.com/krande/paradoc
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A Python library for Parametric Documentation"


extra:
  recipe-maintainers:
    - Krande
